name: sync to upstream

on:
  schedule:
    - cron:  '30 7 * * *'
  workflow_dispatch:

jobs:
  sync_with_upstream:
    name: Sync HEAD with upstream latest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout HEAD
      uses: actions/checkout@v2
      with:
        ref: main
    - name: Pull upstream changes
      id: sync
      uses: bdougie/Fork-Sync-With-Upstream-action@fork
      with:
        upstream_repository: iwdc-oss/sunsetify
        upstream_branch: main
        target_branch: main